### ISSUE TITLE
Make _bottomBar a public property

### ISSUE THREAD

**Issue by mattrichnz** [thrive-now/BottomNavigationBarXF#53]
This is a great wrapper around BottomNavigationBar, but are you able please to make _bottomBar a public property in the renderer?

ie. BottomBar => _bottomBar;

We are using your excellent package, but we would like access to the underlying object so we can further customize with a custom renderer.

**Comment by AlexanderMelchers** [comment]
I agree that there is a lot to be gained for making the `_bottomBar` field a protected property, as this would allow for greater customization as is otherwise possible. Even though a solution now seems to be available, however, the NuGet-package still does not expose the property, and I have, hence, needed to resort to using some reflection to get a the field...
